{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tcomp.fullname" . }}
  labels:
    {{- include "tcomp.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ include "tcomp.authToken" . | b64enc | quote }}
{{- end }}
